### ISSUE TITLE
Cookbook failing to compile with chef-client 14.5.33

### ISSUE THREAD

**Issue by StuporHero** [poise/application#70]
I have this cookbook in my list of dependencies for a run list that is failing with the following message during my chef-client runs:

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/application/libraries/default.rb
================================================================================

FrozenError
-----------
can't modify frozen Array

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:220:in `included'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `include'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `poise_subresource_container'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise.rb:93:in `block in Poise'
  /var/chef/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:45:in `include'
  /var/chef/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:45:in `<class:Resource>'
  /var/chef/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:44:in `<module:Application>'
  /var/chef/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:27:in `<module:Resources>'
  /var/chef/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:24:in `<module:PoiseApplication>'
  /var/chef/cache/cookbooks/application/files/halite_gem/poise_application/resources/application.rb:23:in `<top (required)>'
  /var/chef/cache/cookbooks/application/files/halite_gem/poise_application/resources.rb:17:in `<top (required)>'
  /var/chef/cache/cookbooks/application/files/halite_gem/poise_application/cheftie.rb:17:in `<top (required)>'
  /var/chef/cache/cookbooks/application/libraries/default.rb:19:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:

213:                @container_default
214:              end
215:            end
216:
217:            def included(klass)
218:              super
219:              klass.extend(ClassMethods)
220>>             klass.const_get(:HIDDEN_IVARS) << :@subcontexts
221:              klass.const_get(:FORBIDDEN_IVARS) << :@subcontexts
222:            end
223:          end
224:
225:          extend ClassMethods
226:        end
227:      end
228:    end
229:  end

Additional information:
-----------------------
      Ruby objects are often frozen to prevent further modifications
      when they would negatively impact the process (e.g. values inside
      Ruby's ENV class) or to prevent polluting other objects when default
      values are passed by reference to many instances of an object (e.g.
      the empty Array as a Chef resource default, passed by reference
      to every instance of the resource).

      Chef uses Object#freeze to ensure the default values of properties
      inside Chef resources are not modified, so that when a new instance
      of a Chef resource is created, and Object#dup copies values by
      reference, the new resource is not receiving a default value that
      has been by a previous instance of that resource.

      Instead of modifying an object that contains a default value for all
      instances of a Chef resource, create a new object and assign it to
      the resource's parameter, e.g.:

      fruit_basket = resource(:fruit_basket, 'default')

      # BAD: modifies 'contents' object for all new fruit_basket instances
      fruit_basket.contents << 'apple'

      # GOOD: allocates new array only owned by this fruit_basket instance
      fruit_basket.contents %w(apple)


System Info:
------------
chef_version=14.5.33
platform=oracle
platform_version=6.10
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 07 seconds
```

**Comment by coderanger** [comment]
This was fixed a long while ago in Poise.

**Comment by StuporHero** [comment]
@coderanger What does that mean? You have no deprecation notices pointing us to another cookbook, and my version number matches the current publicly available version of this cookbook, so I'm at a loss as to how to proceed to fix my situation.

**Comment by coderanger** [comment]
As I said, the bug (and fix) was in Poise. You can find the changelog at https://github.com/poise/poise/blob/master/CHANGELOG.md#v282.

**Comment by coderanger** [comment]
(you can also see this in the stack trace)

**Comment by StuporHero** [comment]
@coderanger That still doesn't help me. What do I need to do? This is a transient dependency that I know nothing about, and I'm just trying to get a little bit of help instead of dismissive condescension.

**Comment by coderanger** [comment]
You need to upgrade your version of the `poise` cookbook to 2.8.2. And you are the one asking for unpaid support, not me :-) That means you are expected to do the legwork.

**Comment by StuporHero** [comment]
@coderanger You could have saved us both time by just saying this at the outset: "This was a bug in the Poise cookbook that was [fixed](https://github.com/poise/poise/blob/master/CHANGELOG.md#v282). You should have a dependency on Poise in your metadata.rb file that you should update to 2.8.2. Thank you for using my cookbooks!"

"I function best when I can be face-to-face (or rather keyboard-to-keyboard) with my users, working with them directly to know what solutions will work best for them." If that is true, you should practice it everywhere. Your work is public, after all.

**Comment by coderanger** [comment]
Chef is no longer something I spend time on. I recommend you don't use this anymore.
